BOT_NAME = "gutenberg"

SPIDER_MODULES = ["scrapper.spiders"]
NEWSPIDER_MODULE = "scrapper.spiders"

ROBOTSTXT_OBEY = True

CONCURRENT_REQUESTS = 16
CONCURRENT_REQUESTS_PER_DOMAIN = 8
DOWNLOAD_DELAY = 1.0

USER_AGENT = "Jan Jabrocki AGH Student, sorry if too many requests. Doing it for school project. Contact: jjabrocki@gmail.com"

AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 2.0
AUTOTHROTTLE_MAX_DELAY = 60
AUTOTHROTTLE_TARGET_CONCURRENCY = 12.0
AUTOTHROTTLE_DEBUG = False

RETRY_TIMES = 5
RETRY_HTTP_CODES = [429, 500, 502, 503, 504, 408]

COOKIES_ENABLED = False

ITEM_PIPELINES = {
    "scrapper.pipelines.SQLitePipeLine": 300,
}

FEED_EXPORT_ENCODING = "utf-8"
REACTOR_THREADPOOL_MAXSIZE = 20
